services:

  db:
    image: postgres:17
    container_name: locatech-db

    environment:
      POSTGRES_DB: locatech
      POSTGRES_USER: locatech
      POSTGRES_PASSWORD: locatech123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  frontend:
    image: ghcr.io/rakotoarinosy/locatech-frontend:latest
    container_name: locatech-frontend

    ports:
      - "42000:80"

    restart: unless-stopped

    depends_on:
      - backend

  backend:
    image: ghcr.io/rakotoarinosy/locatech-backend:latest
    container_name: locatech-backend

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8045
      "

    volumes:
      - ./locatech/media:/app/backend/media

    env_file:
      - .env

    depends_on:
      - db

    ports:
      - "8045:8045"

    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: locatech-n8n

    ports:
      - "5678:5678"

    env_file:
      - .env

volumes:
  postgres_data:
  n8n_data: