# Generated by Django 5.2.8 on 2025-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('prix_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(default='disponible', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='materiels/')),
            ],
        ),
    ]
