# Generated by Django 5.2.8 on 2025-11-30 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('loue', 'Loué'), ('maintenace', 'Maintenace'), ('casse', 'Cassé')], default='disponible', max_length=20),
        ),
    ]
