# Generated by Django 5.2.8 on 2026-06-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_fix_maintenance_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('loue', 'Loué'), ('maintenance', 'Maintenance'), ('casse', 'Cassé')], default='disponible', max_length=20),
        ),
    ]
