# Generated by Django 5.2.8 on 2026-06-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_materiel_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materiel',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
