# Generated by Django 5.2.8 on 2025-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('cni', models.ImageField(blank=True, null=True, upload_to='cnis/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
