# Generated by Django 5.2.8 on 2026-06-25 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('materials', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('en cours', 'En cours'), ('confirmee', 'Confirmée — Matériel sorti'), ('en_attente_retour', 'En attente de retour'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en cours', max_length=20)),
                ('retard_jours', models.PositiveIntegerField(default=0)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('montant_recu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mvola', 'MVola'), ('orange', 'Orange Money'), ('virement', 'Virement')], max_length=50, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiel')),
            ],
        ),
    ]
