# Generated by Django 5.2.8 on 2026-06-27 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='materiel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='prix_total',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée — Matériel sorti'), ('en_attente_retour', 'En attente de retour'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.CreateModel(
            name='LigneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materiel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='reservations.reservation')),
            ],
        ),
    ]
