# Generated by Django 5.2.8 on 2026-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_materiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('en cours', 'En cours'), ('confirmee', 'Confirmée — Matériel sorti'), ('en_attente_retour', 'En attente de retour'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
