# Generated by Django 5.2.8 on 2026-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En cours'), ('confirmee', 'Confirmée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en cours', max_length=20),
        ),
    ]
