# Generated by Django 5.2.8 on 2026-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_notes_alter_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mvola', 'MVola'), ('orange', 'Orange Money'), ('virement', 'Virement')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('en cours', 'En cours'), ('confirmee', 'Confirmée — Matériel sorti'), ('en_attente_retour', 'En attente de retour'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en cours', max_length=20),
        ),
    ]
