# Generated by Django 5.2.8 on 2026-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('a_payer', 'À payer'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
