# Generated by Django 5.2.8 on 2026-06-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
        ('reservations', '0004_reservation_notes_alter_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='reservations.reservation'),
        ),
    ]
