# Generated by Django 5.2.8 on 2026-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_facture_numero_facture_statut_alter_facture_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
