# Generated by Django 5.2.8 on 2026-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_alter_facture_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
