# Generated by Django 5.2.8 on 2026-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_alter_facture_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('a_payer', 'À payer'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
